### ISSUE TITLE
Type import broken with TS nodenext

### ISSUE THREAD

**Issue by nickluger** [uploadcare/uploadcare-js-api-clients#436]
### Describe the bug

```
Could not find a declaration file for module '@uploadcare/upload-client'.
```

I guess, it might be caused by the types being defined like this in `upload-client/package.json`
```
  "types": "./dist/types.d.ts",
  "exports": {
    ".": {
      "node": "./dist/index.node.js",
      "browser": "./dist/index.browser.js",
      "default": "./dist/index.browser.js"
    }
  }
```

This is not valid in TS' ESM-support mode (`NodeNext`). The `types` field is only used for legacy projects. New TS > 4.7 projects with `nodenext` mode expect the types to be at `./dist/index.d.ts`.

In case you want to leave the types at their current location, you additionally need to add the `types` definition within the `exports` block, as described here: 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing

Also important:

> Note that the "types" condition should always come first in "exports".

### Expected behavior
TS type imports should work in TS >= 4.7 & NodeNext mode. I assume you intend to support NodeNext, as you moved the package to ESM-only anyway.

### Environment

 - Library version: 5.1.0
 - Language/framework version: Node.js v16.18.0 & TS: 4.8.4

**Comment by nd0ut** [comment]
@nickluger Thank you! 

Yeah, you're right, we missed `types` field inside `exports`.

I added `types` fields and renamed `types.d.ts` to `index.d.ts` but still left an explicitly declared types path.

See [v5.1.1](https://github.com/uploadcare/uploadcare-js-api-clients/releases/tag/v5.1.1)

**Comment by nickluger** [comment]
Yes, seems to work! 

> still left an explicitly declared types path.

Yes, perfect for backwards compatibility.

Thank you for fixing it. 💙
