### ISSUE TITLE
Issue with public key

### ISSUE THREAD

**Issue by cforcross** [uploadcare/uploadcare-js-api-clients#528]
### Describe the bug

Currently on the uploadthing dashboard when u create a new  project on the settings , your being given the 
 **UPLOADTHING_SECRET** and **UPLOADTHING_APP_ID** as you can see, there's no **UPLOADCARE_PUB_KEY** and when i  use the  UPLOADTHING_SECRET i get the error below

![Screenshot 2024-08-30 162300](https://github.com/user-attachments/assets/7ab45f4d-0020-4ff9-a837-97b8249450b7)

Now on my project dashboard, i've created a new key  named  **UPLOADCARE_PUB_KEY** but  i keep getting the error above

### Environment
 - Library version:
 - "@uploadcare/upload-client": "^6.14.1"
 
 - Language/framework version:
 - typescript
 - "next": "14.2.3",
 
 - OS version: 
 - windows 11

**Comment by optlsnd** [comment]
Uploadcare and Uploadthing are different services. To use this library, you need API keys from Uploadacre. You can create an account and obtain the API keys here https://uploadcare.com/.

**Comment by cforcross** [comment]
> Uploadcare and Uploadthing are different services. To use this library, you need API keys from Uploadacre. You can create an account and obtain the API keys here https://uploadcare.com/.
